[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"


[tool.pytest.ini_options]
addopts = "--cov=src"
testpaths = [
    "tests",
]
